apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otel-test-app.fullname" . }}-flask
  labels:
    {{- include "otel-test-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: flask-app
spec:
  replicas: {{ .Values.flaskApp.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: flask-app
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: flask-app
    spec:
      containers:
        - name: flask-app
          image: "{{ .Values.flaskApp.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.flaskApp.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: CELERY_BROKER_URL
              value: {{ include "otel-test-app.redisUrl" . }}
            - name: CELERY_RESULT_BACKEND
              value: {{ include "otel-test-app.redisUrl" . }}
            {{- if .Values.otel.enabled }}
            - name: OTEL_SERVICE_NAME
              value: {{ include "otel-test-app.fullname" . }}-flask
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ include "otel-test-app.otlpEndpoint" . }}
            - name: OTEL_METRICS_EXPORTER
              value: otlp
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: OTEL_LOGS_EXPORTER
              value: otlp
            - name: OTEL_PYTHON_LOG_CORRELATION
              value: "true"
            - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
              value: "true"
            {{- end }}
          resources:
            {{- toYaml .Values.flaskApp.resources | nindent 12 }}
