apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-test-app.fullname" . }}-redis
  labels:
    {{- include "otel-test-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: redis
